// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Admin extends User {
	/**
	 * 
	 */
	public String admin_id;
	/**
	 * 
	 */
	public int status;

	/**
	 * 
	 */
	public void addAuthor() {
	}

	/**
	 * 
	 */
	public void deleteAuthor() {
	}
}
