// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Article implements ParagraphService, PictureService {
	/**
	 * 
	 */
	public Datetime created_at;
	/**
	 * 
	 */
	public String id;
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public Datetime modified_at;
	/**
	 * 
	 */
	public Datetime[] datetime;

	/**
	 * 
	 */
	public void createPara() {
	}

	/**
	 * 
	 */
	public void editPara() {
	}

	/**
	 * 
	 */
	public void deletePara() {
	}

	/**
	 * 
	 */
	public void addPic() {
	}

	/**
	 * 
	 */
	public void removePic() {
	}
}
