// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Author extends User {
	/**
	 * 
	 */
	public String author_id;
	/**
	 * 
	 */
	public boolean isActive;

	/**
	 * 
	 */
	public void varify() {
	}

	/**
	 * 
	 */
	public void assign() {
	}
}
