// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Datetime {
	/**
	 * 
	 */
	public int month;
	/**
	 * 
	 */
	public int day;
	/**
	 * 
	 */
	public int hour;
	/**
	 * 
	 */
	public int min;
	/**
	 * 
	 */
	public int year;
	/**
	 * 
	 */
	public int second;
}
