// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public interface ParagraphService {
	/**
	 * 
	 */
	public void createPara();

	/**
	 * 
	 */
	public void editPara();

	/**
	 * 
	 */
	public void deletePara();
}
