// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public interface PictureService {
	/**
	 * 
	 */
	public void addPic();

	/**
	 * 
	 */
	public void removePic();
}
