// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Project {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public Datetime started_at;
	/**
	 * 
	 */
	public Datetime closed_at;
	/**
	 * 
	 */
	public boolean status;
	/**
	 * 
	 */
	public String project_id;
	/**
	 * 
	 */
	public Datetime[] datetime;
}
