// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public class Team {
	/**
	 * 
	 */
	public String team_id;
	/**
	 * 
	 */
	public String name;
}
