// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ContentManagementSystem;

/************************************************************/
/**
 * 
 */
public abstract class User {
	/**
	 * 
	 */
	public String user_id;
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public Datetime created_at;
	/**
	 * 
	 */
	public Datetime modified_at;
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public Datetime[] datetime;

	/**
	 * 
	 */
	public void register() {
	}

	/**
	 * 
	 */
	public void login() {
	}

	/**
	 * 
	 */
	public void logout() {
	}

	/**
	 * 
	 */
	public void updateProfile() {
	}
}
